# Generated by Django 4.0.1 on 2022-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_purchase_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(blank=True),
        ),
    ]
